import { ref, set, push } from 'firebase/database';
import { database } from '../../firebase'; // Adjust the import path according to your project structure

export default function signInViaProvider() {
  const { data: session, status } = useSession();

    return new Promise(async (resolve, reject) => {
        try {
            const usersRef = ref(database, 'users');
            const newUserRef = push(usersRef); // Generates a unique key

            const userId = newUserRef.key; // Get the unique key generated by push()

            const { name, email } = session.user; // Assuming you can access username from session.user

            // Set user data in Firebase
            await set(ref(database, 'users/' + userId), {
                username: name,
                email: email,
                id: userId, // Storing the generated userId
            });

            resolve("Sign up successful!");
        } catch (error) {
            reject(error.message);
        }
    });
}
