import HomeLayout from "./components/HomeLayout";
import "./globals.css";
import PostState from "./providers/PostProvider";
import AuthProvider from "./providers/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-screen-2xl mx-auto bg-[#FAF9F6]">
        <AuthProvider>
          <PostState>
          <HomeLayout>
              {children}
          </HomeLayout>
          </PostState>
        </AuthProvider>
      </body>
    </html>
  );
}
